### ISSUE TITLE
Fonctions utiles pour le binding

### ISSUE THREAD

**Issue by VLanvin** [VLanvin/ogaml#1]
Il serait peut-être bon de faire un fichier contenant les fonctions et valeurs utiles au binding (qui reviennent plusieurs fois), comme val_some, val_none, some_val, etc...

A voir si elles apparaissent suffisament et si ça vaut le coup de faire un fichier supplémentaire pour ça.

**Comment by TheoWinterhalter** [comment]
Oui, en effet, où le mettre en revanche ?

**Comment by VLanvin** [comment]
C'est là tout le problème... Etant donné que ça pourrait servir à d'autres bindings (comme l'audio) et qu'on pourrait aussi avoir besoin d'un fichier similaire pour des fonctions OCaml, on peut toujours faire un dossier src/utils.

**Comment by TheoWinterhalter** [comment]
Et un fichier `binding.ml` ou un truc du genre ?

**Comment by VLanvin** [comment]
C'est plutôt un fichier C dont on aurait besoin pour l'instant (stubs.c ?). Mais on aura sûrement besoin d'un fichier ml plus tard.

**Comment by TheoWinterhalter** [comment]
Ah oui, en effet ! Pourquoi pas `stubs.c`, ça me va.

**Comment by VLanvin** [comment]
stubs.c étant entièrement intégré à la compilation, je ferme :)
